In [1]:
from pathlib import Path
import pandas as pd, numpy as np, pyarrow.parquet as pq, pyarrow as pa

In [2]:
pff_passing_path = Path('../data_extraction/data/pff/2019/passing_summary.csv')
pff_rushing_path = Path('../data_extraction/data/pff/2019/rushing_summary.csv')
pff_receiving_path = Path('../data_extraction/data/pff/2019/receiving_summary.csv')
pff_blocking_path = Path('../data_extraction/data/pff/2019/offense_blocking_linemen.csv')
pff_defense_summary_path = Path('../data_extraction/data/pff/2019/defense_summary.csv')
pff_run_defense_path = Path('../data_extraction/data/pff/2019/run_defense_summary.csv')
pff_pass_rush_path = Path('../data_extraction/data/pff/2019/pass_rush_summary.csv')
pff_coverage_path = Path('../data_extraction/data/pff/2019/defense_coverage_summary.csv')
df_passing = pd.read_csv(pff_passing_path)
df_rushing = pd.read_csv(pff_rushing_path)
df_receiving = pd.read_csv(pff_receiving_path)
df_blocking = pd.read_csv(pff_blocking_path)
df_defense = pd.read_csv(pff_defense_summary_path)
df_run_defense = pd.read_csv(pff_run_defense_path)
df_pass_rush = pd.read_csv(pff_pass_rush_path)
df_coverage = pd.read_csv(pff_coverage_path)

In [3]:
df_passing

,player,player_id,position,team_name,player_game_count,accuracy_percent,aimed_passes,attempts,avg_depth_of_target,avg_time_to_throw,...,sack_percent,sacks,scrambles,spikes,thrown_aways,touchdowns,turnover_worthy_plays,twp_rate,yards,ypa
0,Anthony Gordon,40119,QB,WASH STATE,13,79.8,645,692,7.2,2.76,...,2.7,20,27,4,30,48,27,3.5,5563,8.0
1,Joe Burrow,28022,QB,LSU,15,81.9,514,527,9.6,2.95,...,5.9,36,47,0,9,60,11,1.7,5668,10.8
2,Cole McDonald,38584,QB,HAWAII,14,72.0,496,511,12.4,2.53,...,3.6,20,27,0,8,33,29,5.0,4135,8.1
3,Bryce Perkins,35299,QB,VIRGINIA,14,71.2,462,498,9.6,2.88,...,7.9,47,51,1,29,22,29,4.6,3542,7.1
4,Shane Buechele,12659,QB,SMU,13,71.6,457,491,10.0,2.41,...,3.0,16,20,1,24,34,13,2.3,3949,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,Jacob Clark,101628,QB,MINNESOTA,1,100.0,1,1,38.0,2.50,...,0.0,0,0,0,0,0,0,0.0,39,39.0
514,Casey Washington,101710,WR,ILLINOIS,1,0.0,1,1,16.0,3.90,...,0.0,0,0,0,0,0,0,0.0,0,0.0
515,Seamus O'Kelly,102853,P,TEXAS ST,1,100.0,1,1,-1.0,2.00,...,0.0,0,0,0,0,0,0,0.0,4,4.0
516,Raykwon Anderson,102919,HB,APP STATE,1,0.0,1,1,-9.0,1.30,...,0.0,0,0,0,0,0,0,0.0,0,0.0
517,Kaylon Geiger,102929,WR,TROY,1,NaN,0,1,NaN,3.10,...,0.0,0,0,0,0,0,1,50.0,0,0.0

In [4]:
df_rushing

,player,player_id,position,team_name,player_game_count,attempts,avoided_tackles,breakaway_attempts,breakaway_percent,breakaway_yards,...,scrambles,targets,total_touches,touchdowns,yards,yards_after_contact,yco_attempt,ypa,yprr,zone_attempts
0,Chuba Hubbard,57373,HB,OKLA STATE,13,328,77,29,49.2,1029,...,0,28,351,21,2090,1300.0,3.96,6.4,0.86,249
1,Jonathan Taylor,57488,HB,WISCONSIN,14,320,87,30,39.3,787,...,0,37,346,21,2002,1256.0,3.93,6.3,2.13,154
2,AJ Dillon,57165,HB,BOSTON COL,12,317,81,21,31.7,538,...,0,16,330,14,1699,1104.0,3.48,5.4,1.56,90
3,Jaret Patterson,77745,HB,BUFFALO,13,313,86,23,35.6,642,...,0,15,325,19,1804,1125.0,3.59,5.8,1.32,243
4,J.K. Dobbins,57366,HB,OHIO STATE,14,301,73,31,47.5,952,...,0,28,324,21,2003,1208.0,4.01,6.7,1.17,243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1561,Terrell Bynum,61804,WR,WASHINGTON,13,1,0,0,0.0,0,...,0,43,32,0,9,1.0,1.00,9.0,1.72,0
1562,Hezekiah Grimsley,61800,WR,VA TECH,11,1,1,0,0.0,0,...,0,14,11,0,3,3.0,3.00,3.0,2.74,0
1563,Jacquez Jones,62983,WR,TENNESSEE,3,1,0,0,0.0,0,...,0,0,1,0,9,1.0,1.00,9.0,0.00,0
1564,Dadrian Taylor,61789,CB,UTSA,1,1,0,0,0.0,0,...,0,0,1,0,-9,0.0,0.00,-9.0,NaN,0
1565,Devin Maddox,64506,WR,TOLEDO,11,1,0,1,100.0,19,...,0,27,15,0,19,3.0,3.00,19.0,1.21,0

In [5]:
{column: column for column in df_rushing.columns.tolist()}

{'player': 'player',
 'player_id': 'player_id',
 'position': 'position',
 'team_name': 'team_name',
 'player_game_count': 'player_game_count',
 'attempts': 'attempts',
 'avoided_tackles': 'avoided_tackles',
 'breakaway_attempts': 'breakaway_attempts',
 'breakaway_percent': 'breakaway_percent',
 'breakaway_yards': 'breakaway_yards',
 'declined_penalties': 'declined_penalties',
 'designed_yards': 'designed_yards',
 'drops': 'drops',
 'elu_recv_mtf': 'elu_recv_mtf',
 'elu_rush_mtf': 'elu_rush_mtf',
 'elu_yco': 'elu_yco',
 'elusive_rating': 'elusive_rating',
 'explosive': 'explosive',
 'first_downs': 'first_downs',
 'franchise_id': 'franchise_id',
 'fumbles': 'fumbles',
 'gap_attempts': 'gap_attempts',
 'grades_hands_fumble': 'grades_hands_fumble',
 'grades_offense': 'grades_offense',
 'grades_offense_penalty': 'grades_offense_penalty',
 'grades_pass': 'grades_pass',
 'grades_pass_block': 'grades_pass_block',
 'grades_pass_route': 'grades_pass_route',
 'grades_run': 'grades_run',
 'grades_run_block': 'grades_run_block',
 'longest': 'longest',
 'penalties': 'penalties',
 'rec_yards': 'rec_yards',
 'receptions': 'receptions',
 'routes': 'routes',
 'run_plays': 'run_plays',
 'scramble_yards': 'scramble_yards',
 'scrambles': 'scrambles',
 'targets': 'targets',
 'total_touches': 'total_touches',
 'touchdowns': 'touchdowns',
 'yards': 'yards',
 'yards_after_contact': 'yards_after_contact',
 'yco_attempt': 'yco_attempt',
 'ypa': 'ypa',
 'yprr': 'yprr',
 'zone_attempts': 'zone_attempts'}

In [6]:
df_receiving

,player,player_id,position,team_name,player_game_count,avg_depth_of_target,avoided_tackles,caught_percent,contested_catch_rate,contested_receptions,...,targeted_qb_rating,targets,touchdowns,wide_rate,wide_snaps,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr
0,James Proche II,48037,WR,SMU,13,10.1,11,67.5,46.5,20,...,107.4,163,15,49.5,254,1219,475,4.3,11.1,2.54
1,Cedric Byrd II,75938,WR,HAWAII,15,11.4,11,66.4,40.0,6,...,93.8,149,10,0.9,6,1101,315,3.2,11.1,1.67
2,Jadan Blue,61705,WR,TEMPLE,13,8.7,10,66.0,33.3,5,...,91.4,144,4,6.4,31,1067,613,6.5,11.2,2.32
3,Omar Bayless,25522,WR,ARK STATE,13,14.2,13,66.0,45.2,14,...,130.7,141,17,93.7,533,1654,612,6.6,17.8,3.12
4,Justin Jefferson,61398,WR,LSU,15,9.4,25,82.8,92.3,12,...,147.9,134,18,0.5,3,1540,714,6.4,13.9,2.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2103,Elijah Barnwell,57387,HB,RUTGERS,4,-3.0,0,100.0,NaN,0,...,100.0,1,0,0.0,0,8,11,11.0,8.0,1.14
2104,Courtney Jackson,99703,WR,SYRACUSE,1,2.0,0,100.0,NaN,0,...,79.2,1,0,0.0,0,3,1,1.0,3.0,0.60
2105,Kamari Morales,99713,TE,N CAROLINA,1,9.0,0,100.0,100.0,1,...,104.2,1,0,0.0,0,9,0,0.0,9.0,9.00
2106,B.J. Baylor,52122,HB,OREGON ST,10,3.0,0,100.0,NaN,0,...,91.7,1,0,0.0,0,6,3,3.0,6.0,0.17
2107,Chris'Seon Stringer,100213,WR,TOLEDO,3,16.0,0,0.0,NaN,0,...,39.6,1,0,80.0,4,0,0,NaN,NaN,0.00

In [7]:
{column: column for column in df_receiving.columns.tolist()}

{'player': 'player',
 'player_id': 'player_id',
 'position': 'position',
 'team_name': 'team_name',
 'player_game_count': 'player_game_count',
 'avg_depth_of_target': 'avg_depth_of_target',
 'avoided_tackles': 'avoided_tackles',
 'caught_percent': 'caught_percent',
 'contested_catch_rate': 'contested_catch_rate',
 'contested_receptions': 'contested_receptions',
 'contested_targets': 'contested_targets',
 'declined_penalties': 'declined_penalties',
 'drop_rate': 'drop_rate',
 'drops': 'drops',
 'first_downs': 'first_downs',
 'franchise_id': 'franchise_id',
 'fumbles': 'fumbles',
 'grades_hands_drop': 'grades_hands_drop',
 'grades_hands_fumble': 'grades_hands_fumble',
 'grades_offense': 'grades_offense',
 'grades_pass_block': 'grades_pass_block',
 'grades_pass_route': 'grades_pass_route',
 'inline_rate': 'inline_rate',
 'inline_snaps': 'inline_snaps',
 'interceptions': 'interceptions',
 'longest': 'longest',
 'pass_block_rate': 'pass_block_rate',
 'pass_blocks': 'pass_blocks',
 'pass_plays': 'pass_plays',
 'penalties': 'penalties',
 'receptions': 'receptions',
 'route_rate': 'route_rate',
 'routes': 'routes',
 'slot_rate': 'slot_rate',
 'slot_snaps': 'slot_snaps',
 'targeted_qb_rating': 'targeted_qb_rating',
 'targets': 'targets',
 'touchdowns': 'touchdowns',
 'wide_rate': 'wide_rate',
 'wide_snaps': 'wide_snaps',
 'yards': 'yards',
 'yards_after_catch': 'yards_after_catch',
 'yards_after_catch_per_reception': 'yards_after_catch_per_reception',
 'yards_per_reception': 'yards_per_reception',
 'yprr': 'yprr'}

In [10]:
df_blocking

,player,player_id,position,team_name,player_game_count,block_percent,declined_penalties,franchise_id,grades_offense,grades_pass_block,...,snap_counts_ce,snap_counts_lg,snap_counts_lt,snap_counts_offense,snap_counts_pass_block,snap_counts_pass_play,snap_counts_rg,snap_counts_rt,snap_counts_run_block,snap_counts_te
0,Taaga Tuulima,38661,C,HAWAII,15,100.0,1,180,66.6,79.3,...,1069,0,0,1069,720,720,0,0,349,0
1,Ilm Manning,75852,T,HAWAII,15,100.0,1,180,66.3,69.4,...,0,0,1067,1067,719,719,0,0,348,0
2,Alan Ali,60053,C,SMU,13,100.0,0,287,54.6,61.0,...,1050,0,0,1051,573,573,0,0,478,0
3,Junior Diaz,26655,C,FAU,14,100.0,0,165,80.3,82.0,...,1047,0,0,1047,583,583,0,0,464,0
4,Brandon Walton,41533,T,FAU,14,100.0,2,165,71.6,84.0,...,0,0,1039,1040,579,579,0,0,461,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5316,Joe Bachie,43250,LB,MICH STATE,1,100.0,0,223,60.0,NaN,...,0,0,0,1,0,0,0,0,1,0
5317,Richie Carpenter Jr.,76757,CB,KENT STATE,1,100.0,0,201,60.0,NaN,...,0,0,0,1,0,0,0,0,1,0
5318,Corbett Glick,83555,QB,S CAROLINA,1,100.0,0,289,60.0,NaN,...,0,0,0,1,0,0,0,0,1,0
5319,Isaiah Stallings,43293,LB,NC STATE,1,100.0,0,248,60.0,NaN,...,0,0,0,1,0,0,0,0,1,0
5320,Joe Tryon-Shoyinka,58272,ED,WASHINGTON,1,100.0,1,340,60.0,NaN,...,0,0,0,1,0,0,0,0,1,0

In [12]:
df_defense

,player,player_id,position,team_name,player_game_count,assists,batted_passes,catch_rate,declined_penalties,forced_fumbles,...,snap_counts_slot,stops,tackles,tackles_for_loss,targets,total_pressures,touchdowns,yards,yards_after_catch,yards_per_reception
0,JR Pace,10116,S,NWESTERN,12,8,0,31.8,0,0,...,355,10,33,0,22,0,1,87,10,12.4
1,Kamal Martin,12744,LB,MINNESOTA,8,18,0,73.9,0,2,...,50,30,40,1,23,7,2,135,100,7.9
2,Reggie Robinson II,13094,CB,TULSA,12,7,1,51.7,0,1,...,24,11,36,2,60,1,1,427,124,13.8
3,Jaylan Foster,13095,CB,S CAROLINA,1,0,0,NaN,0,0,...,4,0,0,0,0,0,0,0,0,NaN
4,Tanner Karafa,13787,DI,BOSTON COL,13,17,2,0.0,0,0,...,0,36,37,3,1,25,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4897,David Miller,148265,CB,NAVY,3,0,0,0.0,0,0,...,0,0,0,0,1,0,0,0,0,NaN
4898,Ke'Vric Wiggins Jr.,150947,CB,LA MONROE,4,0,0,NaN,0,0,...,3,0,1,0,0,0,0,0,0,NaN
4899,Ireland Brown,155565,DI,BOSTON COL,9,1,0,NaN,0,0,...,0,3,5,0,0,3,0,0,0,NaN
4900,Kayode Oladele,158625,ED,MEMPHIS,1,0,0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,NaN
4901,Chris Joyce,169071,CB,TULANE,4,0,0,54.5,0,0,...,32,1,5,0,11,0,1,92,41,15.3

In [13]:
df_run_defense

,player,player_id,position,team_name,player_game_count,assists,avg_depth_of_tackle,declined_penalties,forced_fumbles,franchise_id,...,grades_run_defense,grades_tackle,missed_tackle_rate,missed_tackles,penalties,run_stop_opp,snap_counts_run,stop_percent,stops,tackles
0,JR Pace,10116,S,NWESTERN,12,7,9.9,0,0,256,...,70.0,51.0,17.6,6,3,353,357,2.3,8,21
1,Kamal Martin,12744,LB,MINNESOTA,8,16,3.0,0,0,225,...,72.2,58.3,12.0,6,0,222,226,9.9,22,28
2,Reggie Robinson II,13094,CB,TULSA,12,6,4.2,0,1,320,...,68.8,69.3,10.5,2,8,401,412,1.5,6,11
3,Jaylan Foster,13095,CB,S CAROLINA,1,0,NaN,0,0,289,...,60.0,NaN,NaN,0,0,3,3,0.0,0,0
4,Tanner Karafa,13787,DI,BOSTON COL,13,15,1.7,0,0,121,...,80.8,57.7,14.0,8,1,367,371,8.4,31,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4763,David Miller,148265,CB,NAVY,2,0,NaN,0,0,237,...,60.0,NaN,NaN,0,0,5,5,0.0,0,0
4764,Ke'Vric Wiggins Jr.,150947,CB,LA MONROE,3,0,19.0,0,0,209,...,65.7,73.5,0.0,0,0,27,28,0.0,0,1
4765,Ireland Brown,155565,DI,BOSTON COL,8,1,7.5,0,0,121,...,48.0,75.3,0.0,0,0,68,68,2.9,2,4
4766,Kayode Oladele,158625,ED,MEMPHIS,1,0,NaN,0,0,218,...,60.3,NaN,NaN,0,0,2,2,0.0,0,0
4767,Chris Joyce,169071,CB,TULANE,4,0,12.0,0,0,319,...,73.5,26.6,0.0,0,0,43,43,0.0,0,2

In [14]:
df_pass_rush

,player,player_id,position,team_name,player_game_count,batted_passes,declined_penalties,franchise_id,grades_pass_rush_defense,hits,...,true_pass_set_hurries,true_pass_set_pass_rush_opp,true_pass_set_pass_rush_percent,true_pass_set_pass_rush_win_rate,true_pass_set_pass_rush_wins,true_pass_set_prp,true_pass_set_sacks,true_pass_set_snap_counts_pass_play,true_pass_set_snap_counts_pass_rush,true_pass_set_total_pressures
0,JR Pace,10116,S,NWESTERN,12,0,0,256,59.8,0,...,0,0,0.0,NaN,0,NaN,0,112,0,0
1,Kamal Martin,12744,LB,MINNESOTA,8,0,0,225,67.2,3,...,0,12,15.2,8.3,1,20.8,2,92,14,3
2,Reggie Robinson II,13094,CB,TULSA,12,1,0,320,67.0,0,...,0,0,0.0,NaN,0,NaN,0,42,0,0
3,Tanner Karafa,13787,DI,BOSTON COL,13,2,0,121,62.4,3,...,11,137,100.0,10.2,14,6.9,3,141,141,16
4,Aaron Roberson,13789,CB,LA TECH,13,0,0,208,56.0,1,...,0,2,2.5,0.0,0,25.0,0,80,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3686,Sean Greeley,129513,LB,MARYLAND,1,0,0,215,59.2,0,...,0,0,NaN,NaN,0,NaN,0,0,0,0
3687,Xavier Smith,134137,LB,E CAROLINA,12,0,0,156,52.6,1,...,3,18,16.7,0.0,0,8.3,0,120,20,3
3688,BeeJay Williamson,145255,S,LA TECH,10,0,0,208,64.9,1,...,0,3,3.7,0.0,0,16.7,0,81,3,1
3689,Ireland Brown,155565,DI,BOSTON COL,9,0,0,121,60.2,1,...,1,13,100.0,0.0,0,3.8,0,14,14,1
3690,Kayode Oladele,158625,ED,MEMPHIS,1,0,0,218,60.0,0,...,0,0,NaN,NaN,0,NaN,0,0,0,0

In [15]:
df_coverage

,player,player_id,position,team_name,player_game_count,assists,avg_depth_of_target,catch_rate,coverage_percent,coverage_snaps_per_reception,...,snap_counts_coverage,snap_counts_pass_play,stops,tackles,targets,touchdowns,yards,yards_after_catch,yards_per_coverage_snap,yards_per_reception
0,JR Pace,10116,S,NWESTERN,12,1,14.5,31.8,99.5,57.6,...,427,429,2,12,22,1,87,10,0.2,12.4
1,Kamal Martin,12744,LB,MINNESOTA,8,2,2.9,73.9,88.8,12.6,...,229,258,8,12,23,2,135,100,0.6,7.9
2,Reggie Robinson II,13094,CB,TULSA,12,1,12.0,51.7,98.7,11.2,...,383,388,5,25,60,1,427,124,1.2,13.8
3,Jaylan Foster,13095,CB,S CAROLINA,1,0,NaN,NaN,100.0,NaN,...,2,2,0,0,0,0,0,0,0.0,NaN
4,Aaron Roberson,13789,CB,LA TECH,13,3,11.1,48.3,97.5,10.7,...,156,160,8,16,29,0,146,67,1.0,10.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3492,BeeJay Williamson,145255,S,LA TECH,10,2,13.9,88.2,96.7,13.3,...,206,213,3,9,17,2,244,34,1.2,16.3
3493,Tyrone Lewis Jr.,147159,CB,KANSAS ST,1,0,NaN,NaN,100.0,NaN,...,5,5,0,0,0,0,0,0,0.0,NaN
3494,David Miller,148265,CB,NAVY,2,0,36.0,0.0,100.0,NaN,...,18,18,0,0,1,0,0,0,0.0,NaN
3495,Ke'Vric Wiggins Jr.,150947,CB,LA MONROE,2,0,NaN,NaN,100.0,NaN,...,16,16,0,0,0,0,0,0,0.0,NaN
3496,Chris Joyce,169071,CB,TULANE,4,0,12.0,54.5,100.0,11.3,...,70,70,1,3,11,1,92,41,1.4,15.3

In [18]:
master_col_list = []
dataframes = {
    'df_passing': df_passing,
    'df_rushing': df_rushing,
    'df_receiving': df_receiving,
    'df_blocking': df_blocking,
    'df_defense': df_defense,
    'df_run_defense': df_run_defense,
    'df_pass_rush': df_pass_rush,
    'df_coverage': df_coverage,
}
for name in list(dataframes.keys()):
    print(f"{len(dataframes[name].columns.tolist())} columns added from {name}")
    master_col_list.extend(dataframes[name])
print(f"{len(master_col_list)} columns before deduplicating")
master_col_list = list(set(master_col_list))
print(f"{len(master_col_list)} columns after deduplicating")
master_col_list

42 columns added from df_passing
47 columns added from df_rushing
45 columns added from df_receiving
31 columns added from df_blocking
55 columns added from df_defense
24 columns added from df_run_defense
34 columns added from df_pass_rush
40 columns added from df_coverage
318 columns before deduplicating
176 columns after deduplicating

['batted_passes',
 'pressures_allowed',
 'total_pressures',
 'rec_yards',
 'contested_receptions',
 'true_pass_set_snap_counts_pass_rush',
 'routes',
 'hits_allowed',
 'grades_run_block',
 'breakaway_yards',
 'yprr',
 'true_pass_set_pass_rush_win_rate',
 'grades_pass_rush_defense',
 'bats',
 'declined_penalties',
 'forced_fumbles',
 'tackles_for_loss',
 'slot_snaps',
 'route_rate',
 'dropped_ints',
 'snap_counts_dl_a_gap',
 'true_pass_set_pass_rush_percent',
 'drops',
 'explosive',
 'fumbles',
 'snap_counts_coverage',
 'grades_tackle',
 'avg_time_to_throw',
 'pass_block_percent',
 'pass_rush_wins',
 'tackles',
 'team_name',
 'hurries',
 'first_downs',
 'snap_counts_pass_rush',
 'player_id',
 'touchdowns',
 'qb_rating',
 'stops',
 'stop_percent',
 'true_pass_set_hurries',
 'grades_offense_penalty',
 'snap_counts_lt',
 'grades_hands_fumble',
 'yards_after_contact',
 'yco_attempt',
 'scrambles',
 'sacks_allowed',
 'aimed_passes',
 'position',
 'designed_yards',
 'grades_run',
 'true_pass_set_hits',
 'interceptions',
 'snap_counts_pass_play',
 'zone_attempts',
 'safeties',
 'hurries_allowed',
 'snap_counts_corner',
 'true_pass_set_pass_rush_wins',
 'targets',
 'sacks',
 'player_game_count',
 'elu_rush_mtf',
 'missed_tackle_rate',
 'hits',
 'franchise_id',
 'snap_counts_run_block',
 'grades_run_defense',
 'snap_counts_lg',
 'snap_counts_dl_b_gap',
 'true_pass_set_grades_pass_rush_defense',
 'non_spike_pass_block_percentage',
 'true_pass_set_total_pressures',
 'pass_rush_opp',
 'snap_counts_defense',
 'coverage_percent',
 'grades_coverage_defense',
 'turnover_worthy_plays',
 'block_percent',
 'elu_yco',
 'gap_attempts',
 'avoided_tackles',
 'snap_counts_block',
 'snap_counts_run',
 'grades_offense',
 'avg_depth_of_target',
 'breakaway_percent',
 'snap_counts_run_defense',
 'prp',
 'catch_rate',
 'fumble_recoveries',
 'run_plays',
 'forced_incompletion_rate',
 'assists',
 'grades_defense_penalty',
 'snap_counts_te',
 'scramble_yards',
 'wide_rate',
 'passing_snaps',
 'yards_after_catch_per_reception',
 'missed_tackles',
 'grades_defense',
 'grades_pass_block',
 'interception_touchdowns',
 'pass_block_rate',
 'big_time_throws',
 'true_pass_set_snap_counts_pass_play',
 'total_touches',
 'true_pass_set_sacks',
 'breakaway_attempts',
 'grades_hands_drop',
 'slot_rate',
 'snap_counts_offense',
 'true_pass_set_pass_rush_opp',
 'true_pass_set_batted_passes',
 'btt_rate',
 'attempts',
 'thrown_aways',
 'def_gen_pressures',
 'accuracy_percent',
 'snap_counts_rg',
 'pass_break_ups',
 'forced_incompletes',
 'run_stop_opp',
 'pass_plays',
 'pass_blocks',
 'coverage_snaps_per_target',
 'penalties',
 'snap_counts_pass_block',
 'snap_counts_ce',
 'contested_catch_rate',
 'elu_recv_mtf',
 'yards_per_reception',
 'drop_rate',
 'dropbacks',
 'fumble_recovery_touchdowns',
 'ypa',
 'non_spike_pass_block',
 'player',
 'pass_rush_percent',
 'pbe',
 'hit_as_threw',
 'avg_depth_of_tackle',
 'snap_counts_dl_over_t',
 'completions',
 'snap_counts_rt',
 'yards_per_coverage_snap',
 'snap_counts_box',
 'snap_counts_dl_outside_t',
 'yards',
 'qb_rating_against',
 'inline_rate',
 'snap_counts_offball',
 'snap_counts_fs',
 'receptions',
 'caught_percent',
 'inline_snaps',
 'completion_percent',
 'snap_counts_slot',
 'contested_targets',
 'twp_rate',
 'snap_counts_dl',
 'true_pass_set_prp',
 'targeted_qb_rating',
 'pass_rush_win_rate',
 'coverage_snaps_per_reception',
 'yards_after_catch',
 'longest',
 'sack_percent',
 'wide_snaps',
 'grades_pass_route',
 'elusive_rating',
 'pressure_to_sack_rate',
 'grades_pass',
 'spikes']